### PR TITLE
Adding force undeployment button for UI

### PR DESCRIPTION
**Pull request by anuruddhal**

### CODE REVIEW

**Comment by imesh** [comment]
Anuruddha: The merge process failed with the following:

Falling back to patching base and 3-way merge...
Auto-merging service-stubs/org.apache.stratos.cloud.controller.service.stub/src/main/resources/CloudControllerService.wsdl
Auto-merging components/org.apache.stratos.rest.endpoint/src/main/java/org/apache/stratos/rest/endpoint/util/converter/ObjectConverter.java
CONFLICT (content): Merge conflict in components/org.apache.stratos.rest.endpoint/src/main/java/org/apache/stratos/rest/endpoint/util/converter/ObjectConverter.java
Auto-merging components/org.apache.stratos.common/src/main/java/org/apache/stratos/common/client/CloudControllerServiceClient.java
CONFLICT (content): Merge conflict in components/org.apache.stratos.common/src/main/java/org/apache/stratos/common/client/CloudControllerServiceClient.java
Auto-merging components/org.apache.stratos.cloud.controller/src/main/java/org/apache/stratos/cloud/controller/services/impl/CloudControllerServiceImpl.java

**Comment by anuruddhal** [comment]
Hi Imesh,

I haven't done any changes in classes that have merge conflicts. And in the git hub it says "This pull request can be automatically merged by project collaborators." 

Shall I resend the PR ?

**Comment by imesh** [comment]
Is your local branch up to date with the remote? May be that's the problem.

**Comment by anuruddhal** [comment]
I have now updated branch with remote. 
Can you please try again !

**Comment by imesh** [comment]
Thanks Anuruddha, that worked! I have now merged this pull request to master branch.

**Pull request closed without merging**
