### PR TITLE
Adding monitoring dashboard feature

### PR DESCRIPTION
**Pull request by Thanu**
This p/r is to add monitoring dashboard feature and minor change in metering-dashboard artifacts.
It includes following changes for monitoring dashboard:
1. Adding SystemTimeWindowProcessor extension and introducing timestamp attribute in cep avg stats artifacts.
2. Adding monitoring-dashborad artifacts to das extension.
3. Restructuring stratos-das-extension module.
4. Deleting DefaultWSO2EventOutputAdaptor.xml from cep extension artifacts and stratos distribution.

Also it includes following changes in metering-dashboard artifacts:
1. Updating license headers in outputAdapterUiLibrary.js in Member_Information and Member_Status gadgets.
2. Removing build.xml file in metering-dashboard CApps.

### CODE REVIEW

**Comment by ravihansa3000** [comment]
Integration test SingleClusterScalingTestCase is continuously failing with this. Can you check whether integration tests are passing?

**Comment by Thanu** [comment]
I have started to look into this.

**Comment by ravihansa3000** [comment]
I'm able to successfully build from stratos-4.1.x branch (including tests). But this PR fails continuously at SingleClusterScalingTestCase.

**Comment by Thanu** [comment]
I was able to solve "Too many open files issue" when running integration test locally yesterday. I ran integration-test twice today, for me also SingleClusterScalingTestCase fails with the below error:

Failed tests: 
  SingleClusterScalingTestCase.testDeployApplication:114->assertClusterWithScalingup:206 » ThreadTimeout

I'm checking this further.

**Comment by Thanu** [comment]
Akila I am able to build stratos 4.1.x branch after merging this p/r without any test failures in a clean repo. I have tried to build several times and couldn't produce the above timeout issue also (SingleClusterScalingTestCase.testDeployApplication:114->assertClusterWithScalingup:206 » ThreadTimeout) after clean repo build.

**Comment by Thanu** [comment]
Closing this p/r as it is merged with stratos 4.1.x branch.

**Pull request closed without merging**
