### PR TITLE
Refactoring object converter class

### PR DESCRIPTION
**Pull request by Vishanth**
Refactored the object converter class by fixing the following
> Declaration redundancy
> Java language level migration aids (For loops to foreach)
> Performance issues
> Probable bugs
> Spellings

### CODE REVIEW

**Comment by imesh** [comment]
@Vishanth Would you mind resolving the conflicts in this pull request?
Thanks

**Comment by Vishanth** [comment]
@imesh Will do the needful.
Regards.

**Comment by Vishanth** [comment]
@imesh Sorry the changes removed while working on another task. Will redo this and send a fresh PR.

**Comment by Vishanth** [comment]
Resent in PR https://github.com/apache/stratos/pull/294

**Pull request closed without merging**
